# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d54dfbd784586283bf61122c9bfc4366b4fc0d3692084a3e32a5677f381d354b0586ee0b1cd18fe9713f1c5a37229aa1369acbea1f40cebccce5d3d58647e6e

test:
  secret_key_base: d64e2d3bc73ef379583aec3c3253a73c503e64c0d81e7e276b8b5f70bc8f3dd08f2787c77a995e8a2b5553f6c78fa583e204e1901297bd08a3c0f3a2480f472b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
